### ISSUE TITLE
Dart SDK Version

### ISSUE THREAD

**Issue by marianoarga** [renefloor/flutter_cache_manager#41]
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because flutter_cache_manager >=0.1.0-rc.1 depends on uuid ^0.5.3 and flutter_cache_manager <0.1.0-rc.1 requires SDK version >=1.8.0 <2.0.0, every version of flutter_cache_manager requires uuid ^0.5.3.
Because uuid 0.5.3 requires SDK version >=1.0.0 <2.0.0 and no versions of uuid match >0.5.3 <0.6.0, uuid ^0.5.3 is forbidden.

**Comment by blackmenthor** [comment]
https://github.com/blackmenthor/flutter_cache_manager

i created a fix for this issue, edited the pubspec.yaml for the latest dart sdk

**Comment by chompysticks** [comment]
I just upgraded Flutter on the beta channel and am getting similar issue to @marianoarga:

Because cached_network_image >=0.4.1 depends on flutter_cache_manager ^0.1.1 which depends on uuid ^0.5.3, cached_network_image >=0.4.1 requires uuid ^0.5.3.
So, because uuid >=0.0.7 <1.0.3 requires SDK version <2.0.0 and slam depends on cached_network_image ^0.4.1, version solving failed.

@blackmenthor Any chance of getting the fix available at https://pub.dartlang.org so flutter packages upgrade doesn't fail, would be greatly appreciated 👍

**Comment by Zaxist** [comment]
@chompysticks 
Change your pubspec dependency for flutter_cache_manager to look like this: 

```
flutter_cache_manager: 
    git:
      url: git://github.com/blackmenthor/flutter_cache_manager.git
```

Alternately, fork it to your own github and depend on that url. I have done this for cached_network_image also, which relies on this cache plugin.

```
cached_network_image:
    git:
      url: git://github.com/Zaxist/flutter_cached_network_image.git
```

**Comment by marianoarga** [comment]
@Zaxist thanks, I already forked and fixed the issue in my fork, but I wish the plugin to be updated if is posible
